kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../../../../base/ingress/nginx/public

patchesStrategicMerge:
- |-
  apiVersion: autoscaling/v2
  kind: HorizontalPodAutoscaler
  metadata:
    name: nginx-ingress-controller
  spec:
    minReplicas: 4
    maxReplicas: 6
    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50

- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: nginx-configuration
    namespace: ingress-nginx-public
  data:
    keep-alive-requests: "100000"
    upstream-keepalive-timeout: "30"
