apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: prometheus
spec:
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              resources:
                limits:
                  cpu: "1000m"
                  memory: "3000Mi"
                requests:
                  cpu: "300m"
                  memory: "2500Mi"