kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: elastic-stack-logging

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: os-alerts-pf
    files:
      - pf_authn_exception.json
      - pf_fatal.json
      - pf_invalid_req.json
      - pf_ldap_conn_lost.json
      - pf_pingid_conn_lost.json
      - pf_missing_id.json
      - pf_unexpected_runtime.json