kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: elastic-stack-logging

generatorOptions:
  labels:
    k8s-app: fluent-bit

configMapGenerator:
  - name: fluent-bit-pipeline-cw
    files:
      - cw.conf
  - name: fluent-bit-pipeline-elk
    files:
      - elk.conf
  - name: fluent-bit-pipeline-nr
    files:
      - nr.conf
  - name: fluent-bit-pipeline-s3
    files:
      - s3.conf
  - name: fluent-bit-pipeline-customer
    files:
      - customer.conf