apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-controller
spec:
  template:
    spec:
      initContainers:
        - name: ingress-init
          image: 705370621539.dkr.ecr.us-west-2.amazonaws.com/pingcloud-services/ingress-bootstrap:pdo-7738v2
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            # SigSci needs to be able to write to the root fs
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
          - configMapRef:
              name: ingress-bootstrap-environment-variables
