- op: add
  path: /data
  value:
    main-snippet: load_module /usr/lib/nginx/modules/ngx_http_sigsci_module.so;
    worker-processes: '4'
    max-worker-connections: '0'
    ssl-ciphers: ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
    ssl-dh-param: ingress-nginx-public/dhparam
