apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: prometheus
spec:
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              resources:
                limits:
                  cpu: "400m"
                  memory: "2000Mi"
                requests:
                  cpu: "100m"
                  memory: "1000Mi"