kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: ping-cloud

commonLabels:
  app: ping-cloud
  role: pingdirectory

resources:
  - ../cloud-generic
  - periodic-backup.yaml
  - periodic-csd-upload.yaml
  - periodic-export-ldif.yaml
  - periodic-monitor-log-upload.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: pingdirectory-backup-ops-template-files
    # The following files will be added to cluster as a configmap.
    # The backup-ops.sh will be called later via cronjob or job which will then create
    # these resources (backup-cm, backup-job, and backup-pvc) dynamically.
    files:
      - backup-ops-template/backup-ops.sh
      - backup-ops-template/backup-cm.yaml
      - backup-ops-template/backup-job.yaml
      - backup-ops-template/backup-pvc.yaml

  - name: pingdirectory-restore-ops-template-files
    # The following files will be added to cluster as a configmap.
    # The restore-ops.sh will be called later job which will then create
    # these resources (restore-cm, restore-job, and restore-pvc) dynamically.
    files:
      - restore-ops-template/restore-ops.sh
      - restore-ops-template/restore-cm.yaml
      - restore-ops-template/restore-job.yaml
      - restore-ops-template/restore-pvc.yaml

patchesStrategicMerge:
- discovery-service.yaml
