kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ${K8S_GIT_URL}/k8s-configs/cluster-tools/base/service-discovery?ref=${K8S_GIT_BRANCH}

patches:
# Configure external-dns to only own the hosted zone for the tenant domain
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value:
        --domain-filter=${DNS_ZONE}.
  target:
    group: apps
    kind: Deployment
    name: external-dns
    namespace: external-dns
    version: v1

- patch: |-
    # Add IRSA role annotation to external-dns service account
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: external-dns
      namespace: external-dns
      annotations:
        purpose: service-account-for-external-dns
        ${IRSA_EXTERNAL_DNS_ANNOTATION_KEY_VALUE}
