apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: logstash-elastic
  namespace: elastic-stack-logging
spec:
  template:
    spec:
      containers:
        - name: logstash
          resources:
            limits:
              cpu: "1"
              memory: 4Gi
            requests:
              cpu: "1"
              memory: 4Gi
          env:
            - name: LS_JAVA_OPTS
              value: '-Xms3g -Xmx3g'
            - name: PIPELINE_WORKERS
              value: "6"
            - name: PIPELINE_BATCH_SIZE
              value: "1500"