kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- controller.yaml

patches:
  - target:
      kind: Deployment
      name: sealed-secrets-controller
    patch: | 
      # Changing image to P1AS internal copy
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/bitnami/sealed-secrets-controller:v0.23.1

      # updating cpu/memory limits
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value: 
          limits:
            cpu: 500m
            memory: 100Mi
          requests:
            cpu: 500m
            memory: 100Mi

      # turning off key renewal
      - op: add
        path: /spec/template/spec/containers/0/env
        # SEALED_SECRETS_KEY_RENEW_PERIOD=0 is another way to set flag --key-renew-period=0
        # This turns off the default automatic key renewal that happens every 30 days
        value:
        - name: SEALED_SECRETS_KEY_RENEW_PERIOD
          value: "0"
          
