apiVersion: batch/v1
kind: CronJob
metadata:
  name: pingfederate-periodic-backup
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: pingfederate-backup
              resources:
                limits:
                  cpu: 50m
                  memory: 50Mi
                requests:
                  cpu: 25m
                  memory: 25Mi