apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pingfederate
spec:
  minReplicas: 2
  maxReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: pingfederate
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
      - type: Pods
        value: 1
        periodSeconds: 5
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
       - type: Pods
         value: 1
         periodSeconds: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70