kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: external-dns

resources:
- namespace.yaml
- external-dns-serviceaccount.yaml
- external-dns-clusterrole.yaml
- external-dns-clusterrolebinding.yaml
- external-dns-deployment.yaml

patches:
- target:
    kind: Deployment
    name: external-dns
  patch: |
    - op: add 
      path: /spec/template/spec/securityContext
      value:
          fsGroup: 65534
    - op: add
      path: /spec/template/spec/containers/0/resources
      value:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 300m
            memory: 256Mi
    - op: replace
      path: /spec/template/spec/containers/0/args
      value:
          - --source=service
          - --source-ingress
          - --provider=aws
          - --policy=upsert-only # would prevent ExternalDNS from deleting any records, omit to enable full synchronization
          - --aws-zone-type=public # only look at public hosted zones (valid values are public, private or no value for both)
          - --registry=txt
          - --publish-internal-services
          - --log-level=error