kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: external-dns

resources:
- namespace.yaml
- external-dns-serviceaccount.yaml
- external-dns-clusterrole.yaml
- external-dns-clusterrolebinding.yaml
- external-dns-deployment.yaml

patches:
- patch: | 
    - op: add
      path: /spec/template/spec/securityContext
      value: {}
    - op: add
      path: /spec/template/spec/securityContext/fsGroup
      value: 65534
  target:
    kind: Deployment
    name: external-dns