apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  namespace: prometheus
spec:
  template:
    spec:
      containers:
        - name: prometheus
          resources:
            limits:
              cpu: "1500m"  # 1.5 Cores
              memory: "6Gi"
            requests:
              cpu: "750m"  # 0.75 Cores
              memory: "3Gi"

