apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingaccess-was
$patch: delete

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pingaccess-was
$patch: delete

---
