kind: Component
apiVersion: kustomize.config.k8s.io/v1alpha1

resources:
  - dashboards

configMapGenerator:
  - name: prom-alerts
    namespace: prometheus
    behavior: merge
    files:
      - pgo-prom-alerts.yml
