resources:
- manager.yaml
- manager-upgrade.yaml

patchesStrategicMerge:

- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: pgo
  spec:
    template:
      spec:
        containers:
        - name: operator
          resources:
            requests:
              memory: "100Mi"
              cpu: "10m"
            limits:
              memory: "150Mi"
              cpu: "30m"

- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: pgo-upgrade
  spec:
    template:
      spec:
        containers:
        - name: operator
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
            limits:
              memory: "100Mi"
              cpu: "30m"