---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgo
  labels:
    postgres-operator.crunchydata.com/control-plane: postgres-operator
spec:
  replicas: 1
  strategy: { type: Recreate }
  selector:
    matchLabels:
      postgres-operator.crunchydata.com/control-plane: postgres-operator
  template:
    metadata:
      labels:
        postgres-operator.crunchydata.com/control-plane: postgres-operator
    spec:
      containers:
      - name: operator
        image: postgres-operator
        env:
        - name: PGO_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CRUNCHY_DEBUG
          value: "true"
        - name: RELATED_IMAGE_POSTGRES_14
          value: "public.ecr.aws/r2h3l6e4/pingcloud-clustertools/crunchydata/crunchy-postgres:ubi8-14.7-0"
        - name: RELATED_IMAGE_POSTGRES_14_GIS_3.1
          value: "public.ecr.aws/r2h3l6e4/pingcloud-clustertools/crunchydata/crunchy-postgres-gis:ubi8-14.7-3.1-0"
        - name: RELATED_IMAGE_POSTGRES_14_GIS_3.2
          value: "public.ecr.aws/r2h3l6e4/pingcloud-clustertools/crunchydata/crunchy-postgres-gis:ubi8-14.7-3.2-0"
        - name: RELATED_IMAGE_POSTGRES_14_GIS_3.3
          value: "public.ecr.aws/r2h3l6e4/pingcloud-clustertools/crunchydata/crunchy-postgres-gis:ubi8-14.7-3.3-0"
        - name: RELATED_IMAGE_POSTGRES_15
          value: "public.ecr.aws/r2h3l6e4/pingcloud-clustertools/crunchydata/crunchy-postgres:ubi8-15.2-0"
        - name: RELATED_IMAGE_POSTGRES_15_GIS_3.3
          value: "public.ecr.aws/r2h3l6e4/pingcloud-clustertools/crunchydata/crunchy-postgres-gis:ubi8-15.2-3.3-0"
        - name: RELATED_IMAGE_PGADMIN
          value: "public.ecr.aws/r2h3l6e4/pingcloud-clustertools/crunchydata/crunchy-pgadmin4:ubi8-4.30-10"
        - name: RELATED_IMAGE_PGBACKREST
          value: "public.ecr.aws/r2h3l6e4/pingcloud-clustertools/crunchydata/crunchy-pgbackrest:ubi8-2.41-4"
        - name: RELATED_IMAGE_PGBOUNCER
          value: "public.ecr.aws/r2h3l6e4/pingcloud-clustertools/crunchydata/crunchy-pgbouncer:ubi8-1.18-0"
        - name: RELATED_IMAGE_PGEXPORTER
          value: "public.ecr.aws/r2h3l6e4/pingcloud-clustertools/crunchydata/crunchy-postgres-exporter:ubi8-5.3.1-0"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: { drop: [ALL] }
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      serviceAccountName: pgo
