kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: elastic-stack-logging

# The secret values for config.yml, internal_users.yml, and roles_mapping.yml
# are managed by the p1as-oauth init container, and can be found in the p14c-integration image.
# No secret data here. It's a secret by-design and could be removed in the future

secretGenerator:
  - name: opensearch-securityconfig
    type: Opaque
    files:
      - action_groups.yml
      - allowlist.yml
      - audit.yml
      - nodes_dn.yml
      - roles.yml
      - tenants.yml
generatorOptions:
  disableNameSuffixHash: true
