apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: logstash-elastic
spec:
  template:
    spec:
      containers:
        - name: logstash
          resources:
            limits:
              cpu: "3"
              memory: 8Gi
            requests:
              cpu: "3"
              memory: 8Gi
          env:
            - name: LS_JAVA_OPTS
              value: '-Xms6g -Xmx6g -XX:MaxDirectMemorySize=2g'
            - name: PIPELINE_WORKERS
              value: "24"
            - name: PIPELINE_BATCH_SIZE
              value: "1000"