kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: ping-cloud

commonLabels:
  app: ping-cloud
  role: pingdirectory

resources:
- secret.yaml
- configmap.yaml
- configmap-csd-upload.yaml
- configmap-monitor-log-upload.yaml
- configmap-export-ldif.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: pingdirectory-environment-variables
  envs:
  - env_vars