apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  resources:
    limits:
      cpu: 1500m
      memory: 4500Mi
    requests:
      cpu: 100m
      memory: 1500Mi