apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  namespace: prometheus
spec:
  template:
    spec:
      containers:
        - name: prometheus
          resources:
            limits:
              cpu: "2000m"  # 2 Cores
              memory: "8Gi"
            requests:
              cpu: "1000m"  # 1 Core
              memory: "4Gi"

