apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  resources:
    limits:
      cpu: 2000m
      memory: 6000Mi
    requests:
      cpu: 1000m
      memory: 2000Mi