apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  namespace: prometheus
spec:
  template:
    spec:
      containers:
        - name: prometheus
          resources:
            limits:
              cpu: "3000m"  # 3 Cores
              memory: "10Gi"
            requests:
              cpu: "1500m"  # 1.5 Cores
              memory: "5Gi"

