apiVersion: v1
kind: ConfigMap
metadata:
  name: pingdirectory-backup-ops-template-files
$patch: delete

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: pingdirectory-periodic-backup
$patch: delete

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: pingdirectory-periodic-export-ldif
$patch: delete