kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:

# Deploy cert-manager as part of the bootstrap process so that it's running before its CRD resources are created
- ${K8S_GIT_URL}/k8s-configs/cluster-tools/base/cert-manager/base?ref=${K8S_GIT_BRANCH}

# generate-cluster-state.sh copies this from code-gen/templates/fluxcd/common/
# The minimal bootstrap required for the ping-cloud stack
- ping-cloud.yaml

helmCharts:
  - name: p1as-karpenter
    releaseName: p1as-karpenter
    namespace: kube-system
    version: ${K8S_GIT_BRANCH}-latest
    repo: oci://${ECR_REGISTRY_NAME}/dev
    valuesInline:
      global:
        karpenterEnabled: true
        karpenterCrdEnabled: true
      karpenterController:
        controller:
          env:
            - name: AWS_REGION
              value: ${REGION}
        settings:
          clusterName: ${CLUSTER_NAME}
          interruptionQueue: interruption-${CLUSTER_NAME}
        serviceAccount:
          annotations:
            ${IRSA_KARPENTER_ANNOTATION_KEY_VALUE}
        p1asEC2NodeClass:
          instanceProfile: ${KARPENTER_INSTANCE_PROFILE}