apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: prometheus
spec:
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              resources:
                limits:
                  cpu: "250m"
                  memory: "1300Mi"
                requests:
                  cpu: "100m"
                  memory: "800Mi"