---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
data:
  stream-snippet: |
    map $ssl_preread_server_name $backend {
      "~^pingdirectory-admin\." "pingdirectory.ping-cloud.svc.cluster.local:1636";
      default "127.0.0.1:1636";
    }

    server {
      listen 636;
      ssl_preread on;
      proxy_pass $backend;
    }

    server {
      listen 1636 ssl;
      set $upstream "pingdirectory.ping-cloud.svc.cluster.local:1636";
      proxy_pass $upstream;
      proxy_ssl on;
      ssl_certificate /etc/ingress-controller/ssl/ping-cloud-acme-tls-cert.pem;
      ssl_certificate_key /etc/ingress-controller/ssl/ping-cloud-acme-tls-cert.pem;
    }
---