kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  # PingCloud common resources
  - ${K8S_GIT_URL}/k8s-configs/ping-cloud/${KUSTOMIZE_BASE}/pingcommon?ref=${K8S_GIT_BRANCH}

images:
  - name: ${ECR_REGISTRY_NAME}/pingcloud-services/bootstrap${ECR_ENV}
    newName: 705370621539.dkr.ecr.us-west-2.amazonaws.com/pingcloud-services/bootstrap
    newTag: pdo-7738v2


configMapGenerator:

  # PingCommon environment variables
  - name: pingcommon-environment-variables
    behavior: merge
    envs:
      - ../../env_vars