apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipelines
  labels:
    app: logstash-elastic
data:
  pipelines.yml: |
    - pipeline.id: main
      path.config: "/usr/share/logstash/pipeline/main"
    - pipeline.id: customer
      path.config: "/usr/share/logstash/pipeline/customer"
    - pipeline.id: s3
      path.config: "/usr/share/logstash/pipeline/s3"
    - pipeline.id: cloudwatch
      path.config: "/usr/share/logstash/pipeline/cloudwatch"
    - pipeline.id: newrelic
      path.config: "/usr/share/logstash/pipeline/newrelic"
    - pipeline.id: dlq
      path.config: "/usr/share/logstash/pipeline/dlq"
      pipeline.workers: 1