# Persistent Volume to run restore process
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pingdirectory-restore
  labels:
    class: pingdirectory-server
  annotations:
    volume.autoscaler.kubernetes.io/ignore: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: pingdirectory-gp3
  resources:
    requests:
      storage: ${PINGDIRECTORY_PVC_SIZE}