---
# Cost saving changes happening here
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch-cluster
  namespace: elastic-stack-logging
$patch: delete

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: os-controller-manager
  namespace: elastic-stack-logging
$patch: delete

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-controller
  namespace: ingress-nginx-public
spec:
  replicas: 2

---

$patch: delete
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-ingress-controller
  namespace: ingress-nginx-public

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingaccess-was
  namespace: ping-cloud
spec:
  replicas: 2

---

$patch: delete
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pingaccess-was
  namespace: ping-cloud

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: logstash-elastic
  namespace: elastic-stack-logging
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-bootstrap-completed
        $patch: delete

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipelines
  namespace: elastic-stack-logging
data:
  pipelines.yml: |
    - pipeline.id: customer
      path.config: "/usr/share/logstash/pipeline/customer"
    - pipeline.id: s3
      path.config: "/usr/share/logstash/pipeline/s3"
    - pipeline.id: cloudwatch
      path.config: "/usr/share/logstash/pipeline/cloudwatch"
    - pipeline.id: newrelic
      path.config: "/usr/share/logstash/pipeline/newrelic"

---

# original port is 8080
# that port is turned off as the main pipeline forwards logs to opensearch
# 8081 is used by the s3 bucket pipeline
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: logstash-elastic
  namespace: elastic-stack-logging
spec:
  template:
    spec:
      containers:
      - name: logstash
        readinessProbe:
          httpGet:
            port: 8081
        startupProbe:
          httpGet:
            port: 8081