---
# Cost saving changes happening here
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch-cluster
  namespace: elastic-stack-logging
$patch: delete

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-controller
  namespace: ingress-nginx-public
spec:
  replicas: 2

---

$patch: delete
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-ingress-controller
  namespace: ingress-nginx-public

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingaccess-was
  namespace: ping-cloud
spec:
  replicas: 2

---

$patch: delete
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pingaccess-was
  namespace: ping-cloud