# Delete the CW/NR config to reduce costs in developer CDEs - comment out patch in
# CSR/k8s-configs/REGION/kustomization.yaml in order to enable

apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline-cw
  namespace: elastic-stack-logging
data:

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline-nr
  namespace: elastic-stack-logging
data:

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-pipeline-cw
  namespace: elastic-stack-logging
data:

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-pipeline-nr
  namespace: elastic-stack-logging
data:
