apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingaccess-was
  namespace: ping-cloud
spec:
  replicas: 2

---

$patch: delete
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pingaccess-was
  namespace: ping-cloud

---