apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingaccess-was-admin
$patch: delete

---

apiVersion: v1
kind: Service
metadata:
  name: pingaccess-was-admin
$patch: delete

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: pingaccess-was-periodic-backup
$patch: delete

---

