kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: elastic-stack-logging

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: os-alerts-ingress
    files:
      - nginx-ingress-signal-9.json