apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
spec:
  service:
    ports:
      - port: 12999
        targetPort: 12999
        name: notification
  webhook:
    notification:
      port: "12999"
      endpoint: /notification
      method: POST
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  dependencies:
    - eventName: notification
      eventSourceName: webhook
      name: trigger-opsgenie
      transform:
        script: |-
          event.body.json = {}
          for k, v in string.gmatch(event.body.message, "'(.-)':%s?'(.-)'") do
            event.body.json[k] = v
          end
          return event
  template:
    serviceAccountName: argo-events-sa
  triggers:
    - template:
        http:
          payload:
            - dest: 0.status
              src:
                dataKey: statickey
                dependencyName: trigger-opsgenie
                value: firing
            - dest: 0.labels.severity
              src:
                dataKey: statickey
                dependencyName: trigger-opsgenie
                value: alert
            - dest: 0.generatorURL
              src:
                dataTemplate: '{{ .Input.body.json.APP}}'
                dependencyName: trigger-opsgenie
            - dest: 0.labels.alertname
              src:
                dataTemplate: Backup error in {{ .Input.body.json.APP }}
                dependencyName: trigger-opsgenie
            - dest: 0.labels.k8s_cluster_name
              src:
                dataTemplate: '{{ .Input.body.json.ENVIRONMENT_TYPE}}-{{ .Input.body.json.TENANT_DOMAIN}}'
                dependencyName: trigger-opsgenie
            - dest: 0.annotations.summary
              src:
                dataTemplate: '{{ .Input.body.json.MSG }}'
                dependencyName: trigger-opsgenie
            - dest: 0.annotations.description
              src:
                dataTemplate: '{{ .Input.body.message}}'
                dependencyName: trigger-opsgenie
          url: http://alertmanager.prometheus:9093/api/v1/alerts
        name: opsgenie
---
# Dummy token, it will be replaced by platform injected token.
apiVersion: v1
kind: Secret
metadata:
  name: slack-secret
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
data:
  token: QkFTRTY0LUVOQ09ERUQtT0FVVEgtVE9LRU4=

