---
# Source: opensearch-operator/templates/opensearch-operator-leader-election-rolebinding-rb.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: os-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: os-leader-election-role
subjects:
- kind: ServiceAccount
  name: os-controller-manager
