---
# Source: opensearch-operator/templates/opensearch-operator-metrics-reader-cr.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: os-elastic-stack-logging-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
