---
# Source: p1as-newrelic/charts/nri-bundle/charts/nri-metadata-injection/templates/admission-webhooks/mutatingWebhookConfiguration.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: nri-bundle-nri-metadata-injection
  labels:
    app.kubernetes.io/instance: nri-bundle
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nri-metadata-injection
    app.kubernetes.io/version: 1.15.0
    helm.sh/chart: nri-metadata-injection-4.7.0
webhooks:
  - name: metadata-injection.newrelic.com
    clientConfig:
      service:
        name: nri-bundle-nri-metadata-injection
        namespace: newrelic
        path: "/mutate"
      caBundle: ""
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Ignore
    timeoutSeconds: 28
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]