---
# Source: p1as-newrelic/templates/nr-license-key-secret.tpl
apiVersion: v1
kind: Secret
data:
  NEW_RELIC_LICENSE_KEY: MTIzNDU2Nzg5MGFiY2RlZjEyMzQ1Njc4OTBhYmNkZWYxMjM0NTY3OA==
metadata:
  name: newrelic-license-key
  namespace: newrelic
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
    argocd.argoproj.io/sync-options: Prune=false