---
# Cost saving changes happening here
kind: Deployment
apiVersion: apps/v1
metadata:
  name: opensearch-cluster-dashboards
  namespace: elastic-stack-logging
$patch: delete

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: os-controller-manager
  namespace: elastic-stack-logging
$patch: delete

---

kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: opensearch-cluster-hot
  namespace: elastic-stack-logging
$patch: delete

---

kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: opensearch-cluster-warm
  namespace: elastic-stack-logging
$patch: delete

---

kind: Job
apiVersion: batch/v1
metadata:
  name: opensearch-bootstrap
  namespace: elastic-stack-logging
$patch: delete

--- 

kind: Job
apiVersion: batch/v1
metadata:
  name: opensearch-cluster-securityconfig-update
  namespace: elastic-stack-logging
$patch: delete

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-controller
  namespace: ingress-nginx-public
spec:
  replicas: 2

---

$patch: delete
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-ingress-controller
  namespace: ingress-nginx-public

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingaccess-was
  namespace: ping-cloud
spec:
  replicas: 2

---

$patch: delete
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pingaccess-was
  namespace: ping-cloud
