---
# Cost saving changes happening here
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch-cluster
  namespace: elastic-stack-logging
$patch: delete

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: os-controller-manager
  namespace: elastic-stack-logging
$patch: delete

---