apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-operator-controller-manager
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/grafana-operator/grafana-operator:v5.3.0
