# This secret sets pf.cluster.auth.pwd within profile-repo/pingfederate/instance/bin/run.properties.subst
apiVersion: v1
kind: Secret
metadata:
  name: pingfederate-cluster-auth-password
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
    argocd.argoproj.io/sync-options: Prune=false
type: Opaque
data:
  # Set empty as the default, as not all customers may need.
  PF_CLUSTER_AUTH_PASSWORD: ""