kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: elastic-stack-logging

resources:
- enrichment
- logstash
- namespace.yaml
- opensearch
- os-dashboards

configMapGenerator:
- name: elk-environment-variables
  envs:
  - env_vars