apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pingaccess-was-passwords
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
    argocd.argoproj.io/sync-options: Prune=false
data:
  OLD_PA_ADMIN_USER_PASSWORD: MkFjY2Vzcw==
  PA_ADMIN_USER_PASSWORD: MkZlZGVyYXRlTTByZQ==
