---

groups:
- name: kube-alerts
  rules:
  # Trigger alert when there are 1 or more unscheduled pods for greater than 5+ mins
  - alert: ClusterAutoscalerNumberOfUnscheduledPods
    expr: sum(cluster_autoscaler_unschedulable_pods_count) > 0
    for: 5m
    labels:
      severity: alert
    annotations:
      summary: "Cluster Autoscaler has {{ $value }} unschedulable pods."
      description: "The cluster autoscaler is unable to scale up and is alerting that there are unschedulable pods because of this condition. This may be caused by the cluster autoscaler reaching its resources limits, or by Kubernetes waiting for new nodes to become ready."
      runbook: "https://pingidentity.atlassian.net/l/cp/1m9sGcLD"

  # Trigger warning alert (avoids PagerDuty) when 1 or more volumes are predicted to run out of space within a week.
  - alert: VolumesFullInWeekBasedOnDailyUseRate
    expr: |
      predict_linear(kubelet_volume_stats_available_bytes [1d], 7 * 24 * 60 * 60) <= 0
    for: 10m
    labels:
      severity: warning
    annotations:
      summary:  "PVCs could be full in week according to prediction based on Daily Use Rate. PVC \"{{ $labels.persistentvolumeclaim }}\" located in \"{{ $labels.namespace }}\" namespace."
      description: "To prevent ping-cloud/Infrastructure namespace volumes to become full unexpectedly, there is a prediction based on Daily Use Rate which count what exactly volumes could be full in week. This may be caused by initensive daily usage and needs to be checked to prevent any issues with applications using these volumes."
      runbook: "https://pingidentity.atlassian.net/l/cp/qDQbzSc1"

  # Trigger alert when 1 or more PVCs are using 80% or more of their capacity.
  - alert: RunningPVCsAboveUsedWarningThreshold
    expr: |
      (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes)) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes)) >= (80 / 100)
    for: 10m
    labels:
      severity: alert
    annotations:
      summary: "PVC running above 80% threshold. PVC \"{{ $labels.persistentvolumeclaim }}\" located in \"{{ $labels.namespace }}\" namespace."
      description: "Indicates which PVCs currently running above 80% threshold. To prevent any service interruption, these volumes have to be checked."
      runbook: "https://pingidentity.atlassian.net/l/cp/ttpWJDzW"