kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: prometheus

resources:
  - apiservers-service-monitor.yaml
  - cadvisor-service-monitor.yaml
  - generic-pod-monitor.yaml
  - generic-service-monitor.yaml
  - ksm-service-monitor.yaml
  - nodes-service-monitor.yaml
  - opsgenie-key.yaml
  - pgo-pod-monitor.yaml
  - prometheus.yaml
  - prometheus-agent.yaml
  - prometheus-scrape-config.yaml
  - prometheus-service.yaml
  - rbac.yaml
  - storage.yaml
  - volume-autoscaler
  - prometheus-job-exporter.yaml

configMapGenerator:
- name: prometheus-environment-variables
  options:
    disableNameSuffixHash: true
  envs:
    - env_vars
