apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: crunchy-postgres-exporter
  labels:
    prometheus: agent
spec:
  jobLabel: crunchy-postgres-exporter
  namespaceSelector:
    matchNames:
      - postgres-operator
  selector: {}
  podMetricsEndpoints:
    - tlsConfig:
        insecureSkipVerify: true
      relabelings:
        - sourceLabels: [ __meta_kubernetes_pod_label_postgres_operator_crunchydata_com_crunchy_postgres_exporter,__meta_kubernetes_pod_label_crunchy_postgres_exporter ]
          action: keep
          regex: "true"
          separator: ""
        - sourceLabels: [ __meta_kubernetes_pod_container_port_number ]
          action: drop
          regex: "5432"
        - sourceLabels: [ __meta_kubernetes_pod_container_port_number ]
          action: drop
          regex: "10000"
        - sourceLabels: [ __meta_kubernetes_pod_container_port_number ]
          action: drop
          regex: "8009"
        - sourceLabels: [ __meta_kubernetes_pod_container_port_number ]
          action: drop
          regex: "2022"
        - sourceLabels: [ __meta_kubernetes_pod_container_port_number ]
          action: drop
          regex: "^$"
        - sourceLabels: [ __meta_kubernetes_namespace ]
          targetLabel: kubernetes_namespace
        - sourceLabels: [ __meta_kubernetes_pod_name ]
          targetLabel: pod
        - sourceLabels: [ __meta_kubernetes_pod_label_postgres_operator_crunchydata_com_cluster,__meta_kubernetes_pod_label_pg_cluster ]
          targetLabel: cluster
          separator: ""
          replacement: '$1'
        - sourceLabels: [ __meta_kubernetes_namespace,cluster ]
          targetLabel: pg_cluster
          separator: ":"
          replacement: '$1$2'
        - sourceLabels: [ __meta_kubernetes_pod_ip ]
          targetLabel: ip
          replacement: '$1'
        - sourceLabels: [ __meta_kubernetes_pod_label_postgres_operator_crunchydata_com_instance,__meta_kubernetes_pod_label_deployment_name ]
          targetLabel: deployment
          replacement: '$1'
          separator: ""
        - sourceLabels: [ __meta_kubernetes_pod_label_postgres_operator_crunchydata_com_role ]
          targetLabel: role
        - sourceLabels: [ dbname ]
          targetLabel: dbname
          replacement: '$1'
        - sourceLabels: [ relname ]
          targetLabel: relname
          replacement: '$1'
        - sourceLabels: [ schemaname ]
          targetLabel: schemaname
          replacement: '$1'