apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: kubernetes-services
  labels:
    prometheus: system-monitoring-prometheus
spec:
  tlsConfig:
    insecureSkipVerify: true
  kubernetesSDConfigs:
    - role: endpoints
  relabelings:
    - sourceLabels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
      action: keep
      regex: (true)
    - sourceLabels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
      action: replace
      targetLabel: __scheme__
      regex: (https?)
    - sourceLabels: [__meta_kubernetes_service_annotation_prometheus_io_path]
      action: replace
      targetLabel: __metrics_path__
      regex: (.+)
    - sourceLabels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
      action: replace
      targetLabel: __address__
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:$2
    - action: labelmap
      regex: __meta_kubernetes_service_label_(.+)
    - sourceLabels: [__meta_kubernetes_namespace]
      action: replace
      targetLabel: kubernetes_namespace
    - sourceLabels: [__meta_kubernetes_service_name]
      action: replace
      targetLabel: kubernetes_name
    - sourceLabels: [__meta_kubernetes_pod_name]
      action: replace
      targetLabel: instance