########################################################################################################################
# Customer parameters that are shared by multiple apps
########################################################################################################################

global:

  ############################################################
  # Secrets
  ############################################################
  # Expected format for each secret:
  # NAMESPACE:
  #   KEY1: VALUE1
  #   KEY2: VALUE2
  # Note: NAMESPACE need to match exactly,
  #   but secret keys should follow Helm's camelCase guidance
  ############################################################
  sealedSecrets: false
  secrets:
    ping-cloud:
      ###### Shared Secrets ######

      # License key that is used to enable and point to a NewRelic instance
      newrelicLicenseKey: dW51c2VkCg==
      # Profile Repo SSH Id key secret
      sshIdKeyBase64: "${SSH_ID_KEY_BASE64}"
      
      ###### PingDirectory Secrets #####

      # Used as default password for PD admins
      rootUserPassword: MkZlZGVyYXRlTTByZQ==
      # Mounted as a file on PD container and used for dsreplication commands
      adminUserPassword: MkZlZGVyYXRlTTByZQ==
      # Mounted as a file on PD container and used for encryption/decryption of database
      encryptionPassword: MkZlZGVyYXRlTTByZQ==
      # Backup encryption password
      oldEncryptionPasswords: MkZlZGVyYXRlTTByZQ==
      # An alternative to encryption password in .pin file format
      encryptionSettingsPin: MkZlZGVyYXRlTTByZQ==
      # Client ID to be used with P14C
      p14cClientId: "ODkwNzM2NTQtNGVkMy00YTViLWI4OWMtZmY2YjVlMWI3ZDFi"
      # Client secret to be used with P14C
      p14cClientSecret: "UXA4aTAudHg4U3dVSWphdnlYWn5KYTZLQlA5SzN+azljTUYuUWF4UTZYclBvdHpmOU5DbFk2bHRLLjBJUU42MA=="
      # Environment ID to be tused with P14C
      p14cEnvironmentId: "YzNlMzczNTctNTA2Mi00MWJjLTk5NzItYTdlYTlkMTRhNWEy"
      # The DManager password for new P1AS clients,  who will inherit the default permissions associated with PingDirectory.
      dmanagerPassword: MkZlZGVyYXRlTTByZQ==
      # Default Admin User Password for PingFederate
      pfAdminUserPassword: MkZlZGVyYXRlTTByZQ==
      # Used as default password for PF admin users interacting with PD
      pfLdapPassword: MkZlZGVyYXRlTTByZQ==
      # Password used to authenticate to PD keystore
      acmeCertKeystorePassword: MkZlZGVyYXRlTTByZQ==
      # Secret synced between DelegatedAdmin and PingDirectory
      daOauthTokenValidatorSecret: MkZlZGVyYXRlTTByZQ==
      # Optional license key for PingDirectory
      pingDirectoryLicense: ""
      # Optional certificate(s) to add to the PD truststore. Name must have the prefix "pdTruststore" Ex:
      # pdTruststoreCertOne: "asdfasdf"
      # pdTruststoreCertTwo: "asdfasdf"

  ########################################################
  # Multi-region parameters
  ########################################################
  isMultiCluster: ${IS_MULTI_CLUSTER}

  # primaryRegion is the primary AWS region name
  # the primary region should have the same value for region and primaryRegion
  primaryRegion: "${PRIMARY_REGION}"

  # primaryDnsZone is the primary dns zone for customer for region
  primaryDnsZone: "${PRIMARY_DNS_ZONE}"

  # primaryTenantDomain is the primary domain suffix for customer for region
  # the primary region should have the same value for tenantDomain and primaryTenantDomain
  primaryTenantDomain: "${PRIMARY_TENANT_DOMAIN}"

  # secondaryTenantDomains is an optional comma-separated list of the tenant domain suffixes of secondary regions used
  # for PingFederate adaptive clustering using the JGroups DNS_PING discovery protocol:
  #
  #   - Do NOT include the primary tenant domain in the list
  #   - Do NOT include the CDE prefix in the domain name
  #
  # For example, if the primary domain is "tuna.us1.ping-preview.cloud", then set it
  # to "tuna.eu1.ping-preview.cloud,tuna.au1.ping-preview.cloud" to specify secondary
  # domains in regions eu1 and au1.
  #
  # NOTES:
  #   - Only used in multi-cluster environments. If provided, PF will be configured with DNS_PING.
  #   - It is recommended that SECONDARY_TENANT_DOMAINS be set apriori, even before the
  #     secondary regions are created to avoid pod rollouts. DNS_PING will simply ignore
  #     unreachable domains. If it is not set beforehand, then all servers in the PF
  #     cluster (admin and engines) must be re-rolled to pick up the change.
  secondaryTenantDomains: "${SECONDARY_TENANT_DOMAINS}"

  # globalTenantDomain is the region-independent URL used for DNS failover/routing
  globalTenantDomain: "${GLOBAL_TENANT_DOMAIN}"

  ########################################################
  # S3 buckets
  ########################################################
  # pingArtifactRepoUrl is the ping-hosted common artifacts URL
  pingArtifactRepoUrl: "${PING_ARTIFACT_REPO_URL}"

  # logArchiveUrl is the customer-specific log URL for region
  logArchiveUrl: "${LOG_ARCHIVE_URL}"

  # backupUrl is the customer-specific backup URL for region
  backupUrl: "${BACKUP_URL}"

  ########################################################
  # Miscellaneous ping-cloud variables
  ########################################################
  # pingCloudNamespace is the namespace where Ping apps are deployed
  pingCloudNamespace: "${PING_CLOUD_NAMESPACE}"

  # k8sGitBranch is the ping-cloud-base git branch for base Kubernetes manifests
  k8sGitBranch: "${K8S_GIT_BRANCH}"

  # ecrRegistryName is the name of the Docker image registry
  ecrRegistryName: "${ECR_REGISTRY_NAME}/dev"

  # clusterName is the eks cluster name
  clusterName: "${CLUSTER_NAME}"

  # serverProfileUrl is the git URL for the profile repo
  serverProfileUrl: "${SERVER_PROFILE_URL}"

  # serverProfileBranch is the git branch for the profile repo
  serverProfileBranch: "${SERVER_PROFILE_BRANCH_DERIVED}"

  # Placed in ~/.ssh/known_hosts file to avoid ssh prompts when cloning the cluster state repo
  sshKnownHosts: "${KNOWN_HOSTS_CLUSTER_STATE_REPO}"

  # The image pull policy for all images
  imagePullPolicy: "Always"

  # Boolean determining if this is an isolated microservice or a full PCB deploy
  isMicroserviceDeploy: false

  ########################################################
  # Environment-specific variables
  ########################################################
  # environmentType is used by server profile hooks
  environmentType: "${ENVIRONMENT_TYPE}"

  # env is used by Kubernetes manifests
  env: "${ENV}"

  isBelugaEnv: ${IS_BELUGA_ENV}

  ########################################################
  # DevOps License environment variables
  ########################################################
  pingIdentityDevopsUser: "${PING_IDENTITY_DEVOPS_USER}"
  pingIdentityDevopsKey: "${PING_IDENTITY_DEVOPS_KEY}"

  ########################################################
  # Shared Application Variables
  ########################################################
  # Define the contents for your descriptor.json file here, in yaml. An example is provided below for syntax.  
  # Also see the descriptor.json.readme file in p1as-pingdirectory/deploy/templates/config directory of the 
  # p1as-pingdirectory repo for more info
  # descriptorFile: |-
  #   us-west-2:
  #     hostname: abc
  #     replicas: 1
  #   us-east-2:
  #     hostname: def
  #     replicas: 2
  descriptorFile: ""


  #### FEATURE FLAGS ##################################################################################################
  # Most are disabled by default
  # Please follow runbook instructions for the given feature flag to enable/disable

  # !!! Provisioning for PingFederate is not yet available for multi-region customers !!!
  # Runbook: https://confluence.pingidentity.com/display/PingCloud/How+to+Enable+and+Configure+PingFederate+Provisioning
  pfProvisioningEnabled: ${PF_PROVISIONING_ENABLED}

  radiusProxyEnabled: ${RADIUS_PROXY_ENABLED}

  external_ingress_enabled: ${EXTERNAL_INGRESS_ENABLED}

  # Runbook: https://pingidentity.atlassian.net/wiki/spaces/PDA/pages/427688292/How+to+Enable+and+Disable+Healthchecks+-+1.19.0
  healthchecksEnabled: ${HEALTHCHECKS_ENABLED}
  #####################################################################################################################
