kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- base
- nodepool.yaml

# Setting priority to the deployment of karpenter resources over other manifests in the ArgoCD deployment order.
commonAnnotations:
  argocd.argoproj.io/sync-wave: "-5"

# Point to the ping-cluster-tools repo equivalents pushed to ECR
images:
  - name: public.ecr.aws/karpenter/controller
    newName: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/karpenter/controller
    newTag: v0.33.1

patchesStrategicMerge:
- prometheus-metrics.yaml
- karpenter-deployment.yaml
