apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  namespace: prometheus
spec:
  template:
    spec:
      containers:
        - name: prometheus
          resources:
            limits:
              cpu: "4000m"  # 4 Cores
              memory: "12Gi"
            requests:
              cpu: "2000m"  # 2 Cores
              memory: "6Gi"

