apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  resources:
    limits:
      cpu: 3000m
      memory: 9000Mi
    requests:
      cpu: 1500m
      memory: 4000Mi