kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- base

# Point to the ping-cluster-tools repo equivalents pushed to ECR
images:
  - name: gcr.io/k8s-staging-metrics-server/metrics-server
    newName: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/metrics-server/metrics-server
    newTag: v0.6.4